### ISSUE TITLE
IdentityServer4 with .net core 3.1 InvalidOperationException: Stack empty

### ISSUE THREAD

**Issue by rusunvasile** [seesharper/LightInject.Microsoft.DependencyInjection#118]
Trying to configure a .net core 3.1 app to use IdentityServer4. 

here's the error I'm receiving when trying to reach the well-known URL:

> 
>An unhandled exception occurred while processing the request.
>InvalidOperationException: Stack empty.
>System.Collections.Generic.Stack<T>.ThrowForEmptyStack()

>InvalidOperationException: Unable to resolve type: IdentityServer4.Endpoints.DiscoveryEndpoint, >service name:
>LightInject.ServiceContainer.CreateDelegate(Type serviceType, string serviceName, bool >throwError)

I did specified the following options on container:
 `options.DefaultServiceSelector = serviceNames => serviceNames.SingleOrDefault(string.IsNullOrWhiteSpace) ?? serviceNames.Last();
                    options.EnablePropertyInjection = false;`

Bellow the stack trace: 
System.Collections.Generic.Stack<T>.ThrowForEmptyStack()
System.Collections.Generic.Stack<T>.Pop()
LightInject.Emitter.Emit(OpCode code, ConstructorInfo constructor)
LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action<IEmitter> decoratorTargetEmitMethod)
LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter)
LightInject.ServiceContainer+<>c__DisplayClass205_0.<ResolveEmitMethod>b__0(IEmitter methodSkeleton)
LightInject.ServiceContainer+<>c__DisplayClass162_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
LightInject.ServiceContainer+<>c__DisplayClass162_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action<IEmitter> serviceEmitter)
LightInject.ServiceContainer.CreateDelegate(Type serviceType, string serviceName, bool throwError)

**Comment by seesharper** [comment]
Could you provide a small repro of this? Preferably just push the repo onto GitHub?

**Comment by rusunvasile** [comment]
> Could you provide a small repro of this? Preferably just push the repo onto GitHub?

Just gave you access to the repo

**Comment by seesharper** [comment]
Thanks

**Comment by seesharper** [comment]
Fixed by #119

**Comment by rusunvasile** [comment]
Thank You!
