### ISSUE TITLE
Issues with key ring based data protection in cluster / multi-instance environment.

### ISSUE THREAD

**Issue by stefan505** [seesharper/LightInject.Microsoft.DependencyInjection#14]
I am attempting to generate email reset tokens in one app instance and validate it in another. This is possible with ASP.NET Core as long as I have the following configured for each app:
```
services.AddDataProtection(options => options.ApplicationDiscriminator = "my-app")
    .SetApplicationName("app");
```
This scenario works fine if I stick to ASP.NET's default service container, but by utilising the `CreateServerProvider()` wrapper for LightInject, I started encountering sporadic token verification failures between different instances. After many hours of debugging and research, it appears that the `KeyRingBasedDataProtector` gets the wrong purpose string.

For example:
```
public void ConfigureService(...)
{
    // register stuff
    ...
    var factory = new DefaultServiceProviderFactory();
    var sp = factory.CreateServiceProvider(services);
    var dp = sp.GetDataProtectionProvider();
}
``` 

During start-up, `dp` always has a purpose set to `app`, which is correct as per my config above and payloads can be encrypted / decrypted across multiple app instances.

LightInject example:
```
public void ConfigureService(...)
{
    // register stuff
    ...
    var container = new ServiceContainer();
    var sp = container.CreateServiceProvider(services);
    var dp = sp.GetDataProtectionProvider();
}
``` 

During start-up, `dp` has a sporadically different purpose string. Sometimes its value is  `my-app` (the discriminator in my config above), other times the path of the exe (which I cannot explain). As a result token verification fails randomly when generated on one instance and verifying on another, where the purposes don't match.

Tokens can ONLY be encrypted / decrypted between different apps if the purpose strings on the Data Protection Provider matches. This becomes very important in a clustered environment using load balancing, which is where I'm going with my app.

**Comment by seesharper** [comment]
Might be a scoping issue. What version of LightInject are you using? Is there any way to produce the error in a simpler environment?

**Comment by stefan505** [comment]
I'm using the latest LightInject bits. 

It is very easy to reproduce this with a basic MVC app (with cookie auth) and using my code above via the latest version of VS 2017.

**Comment by seesharper** [comment]
It would be very helpful if you could create a simple repo that produces the error. Then we can PR a solution into that repo

**Comment by stefan505** [comment]
Here you go: https://github.com/stefan505/lightinject-dp-repro

**Comment by seesharper** [comment]
Thanks a lot. Appreciate it. Will look into this his ASAP

**Comment by seesharper** [comment]
Looking into this now and seeing that it pretty consistently gives back the path of the exe on every second run. That is very strange and looks to me that there is something that gets persisted between runs.

**Comment by seesharper** [comment]
It should give back "app" right, not "my-app" or the path of the exe?

**Comment by seesharper** [comment]
Commenting out this line makes them both return the path of the exe 
```
services.AddDataProtection(options => options.ApplicationDiscriminator = "my-app")
                .SetApplicationName("app");
```

**Comment by seesharper** [comment]
```
var options = container.GetInstance<IOptions<DataProtectionOptions>>();
```
This instance sometimes reports the wrong purpose. 
This is a tough one. Might be related to scoping or closure, maybe both. Still investigating

**Comment by seesharper** [comment]
Found it. It is related to multiple services of the same type being registered into the service collection.  
The service is IConfigureOptions&lt;T&gt; that gets added twice through the Configure method. 
Long story short, this relies on services being resolved in the registration order. 
This created a long discussion as you can see here 
https://github.com/aspnet/DependencyInjection/pull/416

Anyhow, we have found a bug in the LightInject adapter that causes the strange behavior.

https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/blob/master/src/LightInject.Microsoft.DependencyInjection/LightInject.Microsoft.DependencyInjection.cs#L90

The offending line caused the multiple services of the same type to be returned in an arbitrary fashion which is why we see this sporadically.

**Comment by stefan505** [comment]
Seems to work thanks!
