### ISSUE TITLE
Update LightInject dependency?

### ISSUE THREAD

**Issue by zpqrtbnk** [seesharper/LightInject.Microsoft.DependencyInjection#19]
Current NuGet package of LightInject.Microsoft.DependencyInjection (2.0.4) says it depends on LightInject >= 5.0.3 _but_ will not work unless LightInject >= 5.1.0 is installed... which can be confusing, as "just" installing LightInject.Microsoft.DependencyInjection on a fresh ASP.NET Core app does not work. Might be worthwhile updating the dependency so the right version of LightInject gets installed?

**Comment by seesharper** [comment]
Thanks for reporting this. 👍 LightInject.Microsoft.DependencyInjection (2.0.5) should be available within a few minutes
