### ISSUE TITLE
Implement IServiceProviderFactory for use in generic hosts

### ISSUE THREAD

**Issue by seesharper** [seesharper/LightInject.Microsoft.DependencyInjection#22]
It seems that if you want to use LightInject with the new generic host in .NET Core 2.1 (Microsoft.Extensions.Hosting) , you have to provide an implementation of IServiceProviderFactory in LightInject.Microsoft.DependencyInjection.

Have a look here: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1#container-configuration
(note the text at the start of the page: "The Generic Host is under development to replace the Web Host in a future release and act as the primary host API in both HTTP and non-HTTP scenarios.).

**Comment by seesharper** [comment]
Something like

```
public static IHostBuilder UseLightInject(this IHostBuilder hostBuilder)
{
    hostBuilder.UseServiceProviderFactory(new LightInjectServiceProviderFactory());
    return hostBuilder;
}

public class LightInjectServiceProviderFactory : IServiceProviderFactory<ServiceContainer>
{
    private IServiceCollection _services;
    private ServiceContainer _serviceContainer;

    public ServiceContainer CreateBuilder(IServiceCollection services)
    {
        _services = services;
        _serviceContainer = new ServiceContainer();
        return _serviceContainer;
    }

    public IServiceProvider CreateServiceProvider(ServiceContainer containerBuilder)
    {
        var provider = containerBuilder.CreateServiceProvider(_services);
        var lifetime = provider.GetService<IApplicationLifetime>();
        lifetime.ApplicationStopped.Register(() => _serviceContainer.Dispose()); //If I don't do this the process will hang when I terminate it (ctrl+c)
        return provider;
    }
}

```

**Comment by seesharper** [comment]
I think this actually calls for a new package as it is not really part of the dependency injection abstractions. 

Maybe something like `LightInject.Microsoft.AspNetCore.Hosting`

**Comment by AmirRaptoR** [comment]
Hi
First i want to thank you for the great library

I`m trying to integrate lightinject(5.2.1) with microsoft hosting (2.1.1). I tried your code and i got InvalidOperationException

InvalidOperationException: Unresolved dependency [Target Type: Microsoft.Extensions.Hosting.Internal.Host], [Parameter: hostLifetime(Microsoft.Extensions.Hosting.IHostLifetime)], [Requested dependency: ServiceType:Microsoft.Extensions.Hosting.IHostLifetime, ServiceName:]

I checked available services of provider and it has all these dependencies registered.

**Comment by AmirRaptoR** [comment]
I found the problem there was 2 ihostlifetime and container couldn't resolve one. I resolve the problem by adding a DefaultServiceSelector.


```
public class LightInjectServiceProviderFactory : IServiceProviderFactory<ServiceContainer>
    {
        private ServiceContainer _serviceContainer;
        private IServiceCollection _services;
        public ServiceContainer CreateBuilder(IServiceCollection services)
        {
            _services = services;
            _serviceContainer = new ServiceContainer(new ContainerOptions
            {
                DefaultServiceSelector = strings => strings.Last()
            });
            return _serviceContainer;
        }
        public IServiceProvider CreateServiceProvider(ServiceContainer containerBuilder)
        {
            var provider = containerBuilder.CreateServiceProvider(_services);
            var lifetime = provider.GetService<IApplicationLifetime>();
            lifetime.ApplicationStopped.Register(() =>
                _serviceContainer.Dispose()); //If I don't do this the process will hang when I terminate it (ctrl+c)
            return provider;
        }
    }

```

**Comment by goldenbeard** [comment]
Hi @seesharper,

I was wondering if there has been any progress made on this issue? I'm in the process of building an app using the .NET Core 2.1 Generic Host with LightInject as the DI container but have encountered the failure to exit problem.

I've tried the code suggested above on 28th May 2018 (registering with IApplicationLifetime.ApplicationStopped) but this doesn't solve the failure to shutdown the app. The registered delegate function is getting called during app shutdown and calls .Dispose() on the service container.

I was wondering if it was something to do with the container root Scope begun by the CreateServiceProvider extension method not being ended, but my knowledge of the internals of how LightInject works is admittedly limited.

Any suggestions would be appreciated.

**Comment by goldenbeard** [comment]
Typically, after spending over a day looking at this I manage to solve it within minutes of posing the question.

I modified the code from above to this:
``` c#
public class LightInjectServiceProviderFactory : IServiceProviderFactory<ServiceContainer>
{
    private IServiceCollection _services;
    private ServiceContainer _serviceContainer;

    public ServiceContainer CreateBuilder(IServiceCollection services)
    {
        _services = services;
        _serviceContainer = new ServiceContainer();
        return _serviceContainer;
    }

    public IServiceProvider CreateServiceProvider(ServiceContainer containerBuilder)
    {
        var provider = containerBuilder.CreateServiceProvider(_services);
        var lifetime = provider.GetService<IApplicationLifetime>();
        lifetime.ApplicationStopped.Register(() => 
        {
            _serviceContainer.Dispose();
            _serviceContainer.ScopeManagerProvider.GetScopeManager(_serviceContainer)
                .CurrentScope.Dispose();
        }); //If I don't do this the process will hang when I terminate it (ctrl+c)
        return provider;
    }
}
```

Please let me know if I'm doing something massively wrong here.

**Comment by seesharper** [comment]
@goldenbeard I don't think you are doing anything massively wrong 😀The LightInject adapter creates a "root" scope which probably would have to be disposed. As long as it works it should be okay. After all this is just before the app ends 😀

**Comment by seesharper** [comment]
@blankensteiner 
> ServiceProviderFactory is part of Microsoft.Extensions.DependencyInjection(.Abstractions) and is used by IHostBuilder which is part of Microsoft.Extensions.Hosting(.Abstractions), so it is not a ASP.NET thing :-)

No but the `UseLightInject` extension method from `LightInject.Microsoft.AspNet.Hosting` extends the `IWebHostBuilder` and not the `IHostBuilder` which is the generic host. Hence the need for another package. The reason I've put this on hold is that the word on the street is that everything will eventually be based on the generic host. But up until now  this is somewhat  unclear. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2

**Comment by seesharper** [comment]
Seems like it is coming though 
https://github.com/aspnet/Hosting/pull/1580#issuecomment-445615340

**Comment by davidfowl** [comment]
Yep!

**Comment by seesharper** [comment]
See https://github.com/seesharper/LightInject.Microsoft.AspNetCore.Hosting

**Comment by goldenbeard** [comment]
Hi @seesharper,
Correct me if I'm wrong, but it doesn't appear that any of the content discussed in this issue is resolved in the new release of seesharper/LightInject.Microsoft.AspNetCore.Hosting?

**Comment by seesharper** [comment]
The `IServiceProviderFactory` was introduced here 
https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/commit/3f235468072374d73fdf1de869adaa95a8001474#diff-4205119d44407f0a3d99f06bfb799c73

Its implementation is in this repo so that it can be used outside of a web host. 

For a .Net3.0 generic host we can do something like 

```
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureServices(services =>
                {
                    services.AddHostedService<Worker>();
                })
                .UseServiceProviderFactory(new LightInjectServiceProviderFactory());
```

We could of course have create a package called `LightInject.Microsoft.Hosting` and had a `UseLightInject` extending the `IHostBuilder`. That would be a very small package though since it will basically just call into `UseServiceFactory` 😀
