### ISSUE TITLE
Is it safe to call CreateServiceProvider more than one time?

### ISSUE THREAD

**Issue by huoshan12345** [seesharper/LightInject.Microsoft.DependencyInjection#31]
In my case, I have to register services in the IServiceCollection after the method `CreateServiceProvider` called(in other words, I want to register services in several IServiceCollection separately, not at the same time). So I want to call CreateServiceProvider more than one time to achieve it. 
Is it safe to do that, is there potential memory leak?

**Comment by seesharper** [comment]
No, that is not supported. What you could do is to merge all service collections before calling CreateServiceProvider
