### ISSUE TITLE
container.CreateServiceProvider() current implementation force PerContainerLifetime

### ISSUE THREAD

**Issue by ivankarpey** [seesharper/LightInject.Microsoft.DependencyInjection#4]
container.CreateServiceProvider() current implementation force PerContainerLifetime

And if there is some services which use `DbContext,` for example

```
class UserService(DbContext ctx){
     ...
}
```

Than using this services will cause to errors like that:

> Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur is you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
> Object name: 'DbContext'.

My vision is that there should be more advanced logic allowing to use standard `LightInject` features.

**Comment by seesharper** [comment]
Can you show me an example where this happens?

**Comment by ivankarpey** [comment]
I push problem code with [this commit](https://github.com/ivankarpey/LightInjectIssue/commit/0c20e039f423ffcfe795a48faad7a21f624e709f). I add test project with integration tests, so currently running this test reproduce the problem

**Comment by ivankarpey** [comment]
Actually I think I found the problem with context. In startup class used it inside using block manually, and looks like it crash everything.  So remove using helps in test code I provide. But in my code I still have different erorrs, like 

> Attempt to create a scoped instance without a current scope.

or something like "Context was used next time when previous time dosen't finished" or somewhat like that, see it only once and can't longer reproduce.

**Comment by seesharper** [comment]
First of all, the integration does not force PerContainerLifetime. It uses a PerContainerScopeManagerProvider which is the class that provides ScopeManagers which in turn keeps track of scopes. Usually this is set to a provider that leverages a ScopeManager that either manages scopes per tread (PerThreadScopeManagerProvier) or per logical call context (PerLogicalCallContextScopeManagerProvider) where the latter is the preferred provider in async/await scenarios. This , however has no meaning in the context of the new DI abstraction in ASP.NET Core since the scopes are maintained by the ASP.NET infrastructure. 

One thing to notice here is that the same error occurs when using the default container (see code below ).
Another thing is that you should probably not resolve services using Task.Run since that may cause ASP.NET to loose track of the current scope. Task.Run on the server should ONLY be used for CPU bound operations since it gets scheduled on the threadpool and fills up very fast once you start hitting your server with many concurrent requests.


```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    services.AddMvc();
    services.AddDbContext<MyContext>(options => options.UseInMemoryDatabase());
    services.AddTransient<IIntService, IntServiceImpl>();

    ServiceContainer ctr = new ServiceContainer();
    
    //**********************************************************************************
    ctr.SetDefaultLifetime<PerRequestLifeTime>(); //this line have no effect since this hard override in ctr.CreateServiceProvider
    //**********************************************************************************
    ctr.RegisterAssembly(typeof(Startup).GetTypeInfo().Assembly);



    //IServiceProvider provider = ctr.CreateServiceProvider(services);
    IServiceProvider provider = services.BuildServiceProvider();
    SetProvider(provider);
    return provider;
}
```

**Comment by ivankarpey** [comment]
In my case things looks a bit harder. In controller I only creating and sending message to a queue, and latter queue dispatch it to handlers. If it's in-memory queue, than dispatching is something similar to Task.Run, in distributed case - it will be separate service listening for messages and invoking handlers.

So you assume this is something like internal Microsoft DI component problem?

**Comment by seesharper** [comment]
If you are returning an in memory representation of some data, you could
just use
```
await Task.FromResult("Whatever");
```

It might be a Microsoft DI problem since the problem you had originally
seems to be present even with the default container.

**Comment by ivankarpey** [comment]
Pretty weird. I still wasn't able to reproduce my case in simplified env, but I made my all test passed using  native MS DI lib, however when using lightinject I still get `attempt to create a scoped instance without a current scope` exception

**Comment by ivankarpey** [comment]
This is my actual handler invoke method for a in-memory queue. Do you see some potential problem which could hurt lightinject?

```
public void Invoke(EventMessage eventMessage, bool waitForComplete = false)
            {
                //Handlers store correspondence between events and it's handlers. Like this
                //{key: typeof(NewUserAddedEvent)
                // value: [typeof(Handler1), typeof(Handler2), typeof(Handler3)]}
                IEnumerable<Type> handlers = _eventToHandlersMap[eventMessage.GetType()];

                List<Task> tasks = new List<Task>();
                handlers.ForEach(
                    h => tasks.Add(Task.Run(() => { _handlerActivator.Resolve(h).Handle((dynamic) eventMessage); })));

                if (waitForComplete || _shouldWait)
                {
                    Task.WaitAll(tasks.ToArray());
                }
            }
```
`_handlerActivator` just encapsulate instance of `IServiceProvider`

**Comment by seesharper** [comment]
Not really. I would be really great if you could try to reproduce this in
the simple demo app though

**Comment by seesharper** [comment]
There is a chance that if you don't wait for the tasks, the web request might finish and the scope might no longer exists. 
http://stackoverflow.com/questions/17577016/long-running-task-in-webapi

**Comment by ivankarpey** [comment]
I think in my case for now tasks is very short (In test cases I just store data in inmemory db), and in tests I have those flag `_shouldWait` so it will wait all tasks completed. I'm a bit busy during a week, but have plans to get back to this problem investigation on a weekend. Maybe will try to debug lightinject sources for a little

**Comment by seesharper** [comment]
Any update on this?

**Comment by ivankarpey** [comment]
Unfortunatelly I wasn't able to decently experiment with this. However in meantime I will need some upgrades on the server, so will try to check the problem again.
