### ISSUE TITLE
LightInject.Microsoft.DependencyInjection unable to resolve services

### ISSUE THREAD

**Issue by navdev** [seesharper/LightInject.Microsoft.DependencyInjection#58]
I am using LightInject.Microsoft.DependencyInjection version 2.1.1 to inject dependencies in Sitecore. Sitecore provides BaseServiceProviderBuilder pipeline processor to inject dependencies. After creating LightInject service provider, it fails to resolve the service while Microsoft service provider is correctly resolving BaseCorePipelineManager service. Sitecore uses version 2.1.1 of Microsoft.Extensions.DependencyInjection.

` 
public class DefaultServiceProviderBuilder : BaseServiceProviderBuilder
    {
        protected override IServiceProvider BuildServiceProvider(IServiceCollection serviceCollection)
        {
            var container = new ServiceContainer() { PropertyDependencySelector = new PropertyInjectionDisabler() };
            var lightInjectProvider = container.CreateServiceProvider(serviceCollection);
            var microsoftProvider = serviceCollection.BuildServiceProvider();
            var t = lightInjectProvider.GetService<BaseCorePipelineManager>(); //returns null
            var t1 = microsoftProvider.GetService<BaseCorePipelineManager>(); //returns Sitecore.Pipelines.DefaultCorePipelineManager
            return microsoftProvider;
        }
    }
`

**Comment by seesharper** [comment]
Could you create a small repro of this?

**Comment by navdev** [comment]
Sure will do that.

**Comment by navdev** [comment]
Create a small repo here https://github.com/navdev/Sitecore.

You will need Sitecore 9.1 to run the solution.

**Comment by seesharper** [comment]
I was not able to restore the packages 

`Errors in packages.config projects
    Unable to find version '12.0.0' of package 'Sitecore.Zip'.
      C:\Users\bri\.nuget\packages\: Package 'Sitecore.Zip.12.0.0' is not found on source 'C:\Users\bri\.nuget\packages\'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Sitecore.Zip.12.0.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      https://api.nuget.org/v3/index.json: Package 'Sitecore.Zip.12.0.0' is not found on source 'https://api.nuget.org/v3/index.json'.
      https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180515-07/final/index.json: Package 'Sitecore.Zip.12.0.0' is not found on source 'https://dotnetfeed.blob.core.windows.net/orchestrated-release-2-1/20180515-07/final/index.json'.`

**Comment by navdev** [comment]
Yes, you need to add Sitecore 9.1 package sources

In Visual Studio go to Tools -> NuGet Package Manager -> Package Manager Settings -> Package Sources and add below url:

https://sitecore.myget.org/F/sc-platform-9-1/api/v3/index.json 

Give it a friendly name.

**Comment by seesharper** [comment]
We have fixed a lot of isses since this was posted. Feel free to reopen if this is still an issue 👍
