### ISSUE TITLE
Method 'GetScopeManager' in type 'LightInject.Microsoft.DependencyInjection.PerContainerScopeManagerProvider'

### ISSUE THREAD

**Issue by MedAnd** [seesharper/LightInject.Microsoft.DependencyInjection#7]
Upgrading our solution to .Net Core latest running on net46 and have come across an issue in Startup.cs with the line:

            return container.CreateServiceProvider(services);

throws the following:

{"Method 'GetScopeManager' in type 'LightInject.Microsoft.DependencyInjection.PerContainerScopeManagerProvider' from assembly 'LightInject.Microsoft.DependencyInjection, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.":"LightInject.Microsoft.DependencyInjection.PerContainerScopeManagerProvider"}

project.json looks something like:

    "AutoMapper": "5.1.1",
    "LightInject": " 5.0.0-RC1",
    "LightInject.Microsoft.DependencyInjection": "1.1.1",
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
    "Microsoft.AspNetCore.Authentication": "1.0.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0",
    "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
    "Microsoft.AspNetCore.Authentication.OpenIdConnect": "1.0.0",
    "Microsoft.AspNetCore.Cors": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Hosting": "1.0.0",
    "Microsoft.AspNetCore.Http.Abstractions": "1.0.0",
    "Microsoft.AspNetCore.Identity": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Mvc.Formatters.Json": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.Server.Kestrel.Https": "1.0.1",
    "Microsoft.AspNetCore.SpaServices": "1.0.0-beta-000019",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.Abstractions": "1.0.0",
    "Microsoft.Extensions.Configuration.Binder": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Swashbuckle": "6.0.0-rc1-final",
    "Swashbuckle.SwaggerGen": "6.0.0-beta901",
    "Swashbuckle.SwaggerUi": "6.0.0-beta901"

The older versions do not throw the exception....

"LightInject": "4.0.10-rc2-2",
"LightInject.Microsoft.DependencyInjection": "1.0.1-rc2-2",

**Comment by seesharper** [comment]
LightInject 5.0.0-RC1 is still not released so you should use the latest non-RC bits.

LightInject 4.1.2
LightInject.Microsoft.DependencyInjection 1.1.1

**Comment by stefan505** [comment]
I'm getting the exact same error as @MedAnd above.

My `project.json` looks like this:

```
 "LightInject.Interception": "2.0.0-RC1",
 "LightInject.Microsoft.DependencyInjection": "1.1.1",  
```

Along with using RC versions for `LightInject` and `LightInject.Interception`, I was hoping to use the RC version for `LightInject.Microsoft.DependencyInjection` as well. I see in the [code](https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/blob/master/src/LightInject.Microsoft.DependencyInjection/LightInject.Microsoft.DependencyInjection.cs#L24), there's a comment referring to `2.0.0-RC1`.

Any reason why this hasn't can't be released as RC yet? Would desperately like to use LightInject in ASP.NET Core.

**Comment by seesharper** [comment]
Working on this right now

**Comment by stefan505** [comment]
Any progress?

**Comment by seesharper** [comment]
A new version has been published to the official NuGet feed
