### ISSUE TITLE
Bug in LightInjectServiceProviderFactory options

### ISSUE THREAD

**Issue by InlineAsm** [seesharper/LightInject.Microsoft.DependencyInjection#87]
Hi,

There is a bug in the constructor of LightInjectServiceProviderFactory that accepts ContainerOptions.

The options are cloned and microsoft settings are applied but then the original options that were passed in are used.

https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/blob/70aa22a9a8481e72200fecd6239210474f60d275/src/LightInject.Microsoft.DependencyInjection/LightInject.Microsoft.DependencyInjection.cs#L285-L287

Regards,
InlineAsm

**Comment by seesharper** [comment]
@InlineAsm Fixed here https://www.nuget.org/packages/LightInject.Microsoft.DependencyInjection/3.1.1
