### ISSUE TITLE
'Attempt to end a scope that is currently not the current scope' error

### ISSUE THREAD

**Issue by stefan505** [seesharper/LightInject.Microsoft.DependencyInjection#9]
I have a controller action that calls into a deep async Task-driven call chain. When an Exception is thrown deep down the chain, the ASP.NET runtime eventually breaks with the following:

```
System.InvalidOperationException: Attempt to end a scope that is currently not the current scope.
   at LightInject.ScopeManager.EndScope(Scope scope)
   at LightInject.Scope.OnCompleted()
   at LightInject.Microsoft.DependencyInjection.LightInjectServiceScope.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesFeature.Dispose()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 6075.0672ms 400 application/json; charset=utf-8
```
Without an error occurring the call chain completes successfully.

I'm using all the very latest ASP.NET Core + LightInject bits.

**Comment by seesharper** [comment]
Are you able to reproduce this in a minimal project?

**Comment by stefan505** [comment]
I've tried one already prior to raising the issue, but it wasn't reproducible then. Giving it a further go now and will advise.

**Comment by seesharper** [comment]
Try this when creating the container.

```
container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
```

**Comment by stefan505** [comment]
Yeah, already tried that before as well, same result.

**Comment by seesharper** [comment]
Okay and we are on the latest bits? LightInject 5.0 and LightInject.Microsoft.DependencyInjection 2.0?

**Comment by stefan505** [comment]
Yip, that's what I'm using along mostly 1.1 ASP.NET Core bits.

**Comment by seesharper** [comment]
What kind of exception is originally thrown from ASP.NET?

**Comment by stefan505** [comment]
There's exceptions thrown and handled within our codebase. We have our own Middleware and Filter that executes pre and post the controller action and the error I listed above is the first (and only) one thrown from ASP.NET. This occurs post the Middleware `Invoke(...)`.

I have to add as well, that by adding `container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();` actually causes the error logged for this issue in one particular condition where I step into the first async method from with the controller action and return immediately back to the controller. By removing the line, the error goes away. The idea to return immediately within the first async method is to try and figure out where in our call chain does it cause the break.

Other than that, I'm still trying to put together a repro that is useful for you to look at.

**Comment by seesharper** [comment]
Great. I would really appreciate a repro of this

**Comment by stefan505** [comment]
I'm still struggling with a repro. 

I've pulled in all the LightInject sources and found that [this line](https://github.com/seesharper/LightInject/blob/master/src/LightInject/LightInject.cs#L5941) has `CurrentScope` as null, which results in the ex.

It becomes null [here](https://github.com/seesharper/LightInject/blob/master/src/LightInject/LightInject.cs#L6141) with `previosScope` being null.

Don't know if that helps at all.

**Comment by seesharper** [comment]
At least we know that the Current scope is null.  It is probably related to the exception being marshaled out of the current call context somehow.  I might have a solution for it too, but it would be very useful to see it fail. Again, thanks for your effort to track this down

**Comment by stefan505** [comment]
By adding `container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();` I discovered this when the request completed:

![image](https://cloud.githubusercontent.com/assets/10812446/21881256/0f8e0efa-d8ac-11e6-97a2-06f7e9132a14.png)

I inspected some variables and discovered:

![image](https://cloud.githubusercontent.com/assets/10812446/21881279/3f9d97be-d8ac-11e6-931e-9fa8df727709.png)

It seems that `CurrentScope` is not equal to `scope`, but to `scope.ParentScope`:

![image](https://cloud.githubusercontent.com/assets/10812446/21881320/6d406ba6-d8ac-11e6-9a03-004839fcdbaf.png)

Still no luck with the repro.

**Comment by seesharper** [comment]
we have another issue that is related to this. btw, is this an IIS app or a console app?

**Comment by stefan505** [comment]
Its a console app at the moment. 

Some more info: 

1. When running as `container.ScopeManagerProvider = new PerThreadScopeManagerProvider()`
if the current thread id changes deep down in our call chain where an Exception is raised, this logged issue occurs with `CurrentScope` null and `scope` not. If I step through the code line by line slowly from the controller up until the point where the Exception is raised, the thread id doesn't change and this logged issue doesn't occur.

2. When running as `container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider()` this logged issue occurs regardless if the thread id changes, with `CurrentScope` differing from `scope` whereby `scope.ParentScope` is actually equal to `CurrentScope` as per my comment above.

**Comment by stefan505** [comment]
See my comment on https://github.com/seesharper/LightInject/issues/339. Pretty sure its the thread id that changes that is causing problems.

**Comment by seesharper** [comment]
The PerLogicalCallContextScopeManagerProvider uses AsyncLocal<T> under the covers to store the current scope. This should return the current scope regardless of the thread. Investigating this now

**Comment by stefan505** [comment]
I understand, from my earlier comments, I refer to the fact that the `CurrentScope` and `scope` becomes "out of sync" so to speak. I suspect if that is fixed, then the use of `PerLogicalCallContextScopeManagerProvider` should work fine 100% of the time.

**Comment by seesharper** [comment]
The whole purpose of this is to provide a scope manager that is tied to the current web request. We might need another storage mechanism here that is based on the the current HttpRequest rather that relying on AsyncLocal<T>. In other works, we might need a PerHttpContextScopeManagerProvider. In legacy ASP.NET applications that is based on System.Web we store the scope manager in the HttpContext.Current.Items collection. We need something similar for .Net Core ASP.NET apps.
http://www.strathweb.com/2016/12/accessing-httpcontext-outside-of-framework-components-in-asp-net-core/

**Comment by stefan505** [comment]
As it stands, I cannot use `PerLogicalCallContextScopeManagerProvider` since it breaks every time I call into my Api, so I'm defaulting to `PerThreadScopeManagerProvider` at the moment. However, this also fails under certain conditions as mentioned before. 

The question is, where to from here? Will you try and fix the issues? Or will you look at a `PerHttpContextScopeManagerProvider`? 

I have to decide quickly what route to take, whether to stay with LightInject or seek alternatives for `LightInject`, `LightInject.Interception` and `LightInject.Microsoft.DependencyInjection` within our greater solution.

**Comment by seesharper** [comment]
I am working on this now. A PerHttpContextScopeManagerProvider is the safest bet in the case of a .Net Core application. I'll keep you posted

**Comment by seesharper** [comment]
LightInject 5.0.0 introduces the ability to resolve instances directly from the scope and actually simplifies the integration with .Net Core dependency injection.

Since ASP.NET dependency injection manages its own scope meaning that it know when a scope should be created and it known when it should be ended. It also keeps a reference to the scope so there is really no need for an ambient scope.



Try to use this simplified scope manager 

```
    internal class StandaloneScopeManager : IScopeManager
    {
        public StandaloneScopeManager(IServiceFactory serviceFactory)
        {
            this.ServiceFactory = serviceFactory;
        }

        public Scope BeginScope()
        {
            CurrentScope = new Scope(this, CurrentScope);
            return CurrentScope;
        }

        public void EndScope(Scope scope)
        {
            CurrentScope = scope.ParentScope;
        }
        
        public Scope CurrentScope { get; set; }

        public IServiceFactory ServiceFactory { get; }
    }

    public class StandaloneScopeManagerProvider : ScopeManagerProvider
    {
        protected override IScopeManager CreateScopeManager(IServiceFactory serviceFactory)
        {
            return new StandaloneScopeManager(serviceFactory);
        }
    }
```

**Comment by stefan505** [comment]
Works a charm! 🥇 🥇

**Comment by stefan505** [comment]
Will the `StandaloneScopeManager` be added to this lib going forward?

**Comment by seesharper** [comment]
This is probably something that should go into the the core LightInject library. The name may change though :) I just need to think a little about how to document this :)

**Comment by stefan505** [comment]
Excellent, thanks very much for the assistance. Greatly appreciated! 👍

**Comment by seesharper** [comment]
### IMPORTANT 

I was a little quick with the solution I gave you. You will quickly run into a race condition when you start to put load on your server. We need to store the current scope per thread like this.

```
    internal class StandaloneScopeManager : IScopeManager
    {
        private readonly ThreadLocal<Scope> currentScope = new ThreadLocal<Scope>();

        public StandaloneScopeManager(IServiceFactory serviceFactory)
        {
            ServiceFactory = serviceFactory;
        }

        public Scope BeginScope()
        {
            var scope = new Scope(this, null);
            currentScope.Value = scope;
            return scope;
        }

        public void EndScope(Scope scope)
        {
            currentScope.Value = null;
        }

        public Scope CurrentScope
        {
            get { return currentScope.Value; }
            set { currentScope.Value = value; }
        }

        public IServiceFactory ServiceFactory { get; }
    }
```

**Comment by stefan505** [comment]
Thanks, I've implemented it.

**Comment by geirsagberg** [comment]
Chiming in here, had the same problem, the `StandaloneScopeManager` fixed it 👍

**Comment by grehovm** [comment]
hello, i have the same error. I found that you removed StandaloneScopeManager from source. Why? And what I have to use to solve a problem?

**Comment by stefan505** [comment]
@seesharper , I am also wondering why removal of `StandaloneScopeManager `? I still have it my source code, should I keep it?

**Comment by geirsagberg** [comment]
I also found a need to keep using the `StandaloneScopeManager`. However I ran into some async trouble, and resorted to using the `LogicalThreadStorage` from LightInject:

```csharp
internal class StandaloneScopeManager : IScopeManager
    {
        private readonly LogicalThreadStorage<Scope> currentScope = new LogicalThreadStorage<Scope>();

        public StandaloneScopeManager(IServiceFactory serviceFactory)
        {
            ServiceFactory = serviceFactory;
        }

        public Scope CurrentScope
        {
            get { return currentScope.Value; }
            set { currentScope.Value = value; }
        }

        public IServiceFactory ServiceFactory { get; }

        public Scope BeginScope()
        {
            var scope = new Scope(this, null);
            currentScope.Value = scope;
            return scope;
        }

        public void EndScope(Scope scope)
        {
            currentScope.Value = null;
        }
    }

    public class StandaloneScopeManagerProvider : ScopeManagerProvider
    {
        protected override IScopeManager CreateScopeManager(IServiceFactory serviceFactory)
        {
            return new StandaloneScopeManager(serviceFactory);
        }
    }
```
